name: Node.js CI

# Run on pushes and PRs to main, and allow manual runs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: shorturl-test
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 20s

    strategy:
      matrix:
        # Use the active LTS stream for Node.js
        node-version: ['lts/*']

    env:
      CI: true
      MONGODB_URI: mongodb://localhost:27017/shorturl-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # enable automatic caching of npm (uses package-lock.json by default)
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Build
        run: npm run build --if-present

      - name: Verify MongoDB Connection
        run: |
          echo "Waiting for MongoDB to be ready..."
          timeout 30 bash -c 'until mongosh --eval "db.runCommand({ ping: 1 })"; do sleep 2; done'
          echo "MongoDB is ready!"

      - name: Run tests
        run: npm test --if-present
        env:
          MONGODB_URI: mongodb://localhost:27017/shorturl-test
